{
 "title": "Segui Tus Compras",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Salud del sistema y JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "El servicio está corriendo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"backend:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime desde el arranque",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Infraestructura y disponibilidad",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Carga General del Sistema",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  # Uso de CPU (promedio últimos 5m)\r\n  avg(process_cpu_usage) * 100\r\n  +\r\n  # Uso de memoria JVM (heap)\r\n  (sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})) * 100\r\n  +\r\n  # Uso de threads (activos vs máx permitidos)\r\n  (sum(executor_active_threads) / sum(executor_pool_max_threads)) * 100\r\n) / 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sesiones activas actuales",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metricas De Negocio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total de requests procesadas (tráfico general)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Tiempo máximo de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri!~\"/actuator.*\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Productos buscados",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "product_searches_total", "legendFormat": "{{query}}" }
   ]
  },
  {
   "title": "Total de vistas por producto",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "product_views_total", "legendFormat": "product_id: {{product_id}}" }
   ]
  },
  {
   "title": "Endpoints con mayor carga",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \r\n  sum by(uri, method) (\r\n    rate(http_server_requests_seconds_count{uri!~\"/actuator.*|/prometheus\"}[5m])\r\n  )\r\n) ",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Usuario Logueados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "user_login_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Usuarios Registrados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "user_registration_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compras por Producto",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort(product_purchases_total)", "legendFormat": "{{product_id}}" }
   ]
  },
  {
   "title": "Total de compras por usuario",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "user_purchases_total", "legendFormat": "UserId: {{user_id}}" }
   ]
  },
  {
   "title": "Favoritos por usuario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    { "expr": "user_favorites_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Número actual de favoritos por producto",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(product_favorites_current)",
     "legendFormat": "{{product_id}}"
    }
   ]
  },
  {
   "title": "Comentarios por Producto",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (product_id) (product_comments_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}